#!/bin/bash

for arg do
 if [[ ${arg##*.} == "pdf"  ]]; then
  BASE="${arg%.*}"
  gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=${BASE}-reduced.pdf $arg
  # 	-dPDFSETTINGS: ebook, screen, print, default  
  # 	-dColorImageResolution: 150
  #
  # Alternatively: 
  # convert -density 200x200 -quality 60 -compress jpeg $arg ${BASE}-reduced.pdf ##(per scansioni) #-resize 50.0%
 else
  zenity --info --text="Not a PDFfile\nIgnoring it.." 
 fi
done
exit
