#!/bin/bash

#echo -n "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | xsel -b -i
#echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | zenity --text-info
#echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | /usr/bin/xclip

xsel -b -o | tail -n 1 | sed 's,file://,,g' #| xsel -b -i
