#!/bin/bash

#----------------------------------------------------------------------------
DEBUG=1;       # esegue
#DEBUG=""       # finge
function debug () { if [[ -z $DEBUG ]]; then echo $@; else $@; fi; }
#----------------------------------------------------------------------------

user="admin"
password="pwd_l0n155"
xnat="https://nextmr01.ge.infn.it:8443/xnat"
DCMREMAP="/home/sensi/fra@09/dicomtoolbox/DicomBrowser-1.5.2/bin/DicomRemap"
REMAPDATA="/tmp/remapdata"
PROJECT="XXX0"


for arg;
do
if [[ -d $arg ]]; then
	     SESS=$(zenity --forms --title="Send to Xnat" --text="Enter scan label" --separator="," --add-entry="Scan Name" --add-entry="File Type")
	     PTID=$(echo $SESS| awk -F"," '{print $1}'| awk -F"_" '{print $1}')
	     SCAN=$(echo $SESS| awk -F"," '{print $1}')
	     SESSION=$(echo $SCAN| awk -F"_" '{print $1"_"$2"_"$3}')


cat << EOF > $REMAPDATA
// NRG sample anonymization script v. 001, 2010-06-21
// by Kevin Archie <karchie@wustl.edu>
- (0008,0014)		// Instance Creator UID
- (0008,0050)		// Accession Number
- (0008,1111)		// Referenced Performed Procedure Step SQ
- (0008,1120)		// Referenced Patient SQ
- (0008,1140)		// Referenced Image SQ
- (0008,0090)		// Referring Physician's Name
- (0008,0096)		// Referring Physician Identification SQ
- (0008,1032)		// Procedure Code SQ
- (0008,1048)		// Physician(s) of Record
- (0008,1049)		// Physician(s) of Record Identification SQ
- (0008,1050)		// Performing Physicians' Name
- (0008,1052)		// Performing Physician Identification SQ
- (0008,1060)		// Name of Physician(s) Reading Study
- (0008,1062)		// Physician(s) Reading Study Identification SQ
- (0008,1110)		// Referenced Study SQ
- (0008,1111)		// Referenced Performed Procedure Step SQ
- (0008,1250)		// Related Series SQ
- (0008,9092)		// Referenced Image Evidence SQ
- (0010,0010)		// Patient's Name
- (0010,0020)		// Patient ID
- (0010,0021)		// Issuer of Patient ID
- (0010,0030)		// Patient's Birth Date
- (0010,0032)		// Patient's Birth Time
- (0010,0050)		// Patient's Insurance Plan Code SQ
- (0010,0101)		// Patient's Primary Language Code SQ
- (0010,1000)		// Other Patient IDs
- (0010,1001)		// Other Patient Names
- (0010,1002)		// Other Patient IDs SQ
- (0010,1005)		// Patient's Birth Name
- (0010,1010)		// Patient's Age
- (0010,1040)		// Patient's Address
- (0010,1060)		// Patient's Mother's Birth Name
- (0010,1080)		// Military Rank
- (0010,1081)		// Branch of Service
- (0010,1090)		// Medical Record Locator
- (0010,2000)		// Medical Alerts
- (0010,2110)		// Allergies
- (0010,2150)		// Country of Residence
- (0010,2152)		// Region of Residence
- (0010,2154)		// Patient's Telephone Numbers
- (0010,2160)		// Ethnic Group
- (0010,2180)		// Occupation
- (0010,21A0)		// Smoking Status
- (0010,21B0)		// Additional Patient History
- (0010,21C0)		// Pregnancy Status
- (0010,21D0)		// Last Menstrual Date
- (0010,21F0)		// Patient's Religious Preference
- (0010,2203)		// Patient's Sex Neutered
- (0010,2297)		// Responsible Person
- (0010,2298)		// Responsible Person Role
- (0010,2299)		// Responsible Organization
// (0012,0063) := "nextmr-anonymized"
- (0020,9221)		// Dimension Organization SQ
- (0020,9222)		// Dimension Index SQ
- (0038,0010)		// Admission ID
- (0038,0011)		// Issuer of Admission ID
- (0038,0060)		// Service Episode ID
- (0038,0061)		// Issuer of Service Episode ID
- (0038,0062)		// Service Episode Description
- (0038,0500)		// Patient State
- (0038,0100)		// Pertinent Documents SQ
- (0040,0260)		// Performed Protocol Code SQ
- (0088,0130)		// Storage Media File-Set ID
- (0088,0140)		// Storage Media File-Set UID
- (5200,9229)		// Shared Functional Groups SQ
- (0008,0021)		// Series Date
(0010,4000) := PatientComments 
PatientComments := "Project:$PROJECT;Subject:$PTID;Session:$SESSION" 
(0020,0011) := SeriesNumber
SeriesNumber := "$SCAN"
EOF
	out_dicomdir=$(mktemp -d);
	tail -n 5 $REMAPDATA
	$DCMREMAP -d $REMAPDATA -o $out_dicomdir $arg
	if [[ $(echo $?) -ne 0 ]];then echo "error";exit;fi

	zip -rj ${out_dicomdir}.zip ${out_dicomdir}/*
	if [[ $(echo $?) -ne 0 ]]; then echo "error";exit;fi
	debug curl -u $user:$password --insecure -w "%{http_code}" --form project="$PROJECT" --form "image_archive=@${out_dicomdir}.zip" "$xnat/data/services/import?format=html&overwrite=delete" | zenity --text-info --height=500 --width=400 --title="Send to Xnat?"
	if [[ $(echo $?) -ne 0 ]]; then echo "error";exit;fi


elif [[ -f $arg ]]; then
    	SESS=$(zenity --forms --title="Send to Xnat" --text="Enter scan label" --separator="," --add-entry="Scan Name" --add-entry="File Type")
	PTID=$(echo $SESS| awk -F"," '{print $1}'| awk -F"_" '{print $1}')
	TYPE=$(echo $SESS| awk -F"," '{print $2}')
	SCAN=$(echo $SESS| awk -F"," '{print $1}')
    	debug ~/upsingle3.sh $PTID "/tmp/fake/" $SCAN $arg $TYPE | zenity --text-info --height=500 --width=400 --title="Send to Xnat?"
	if [[ $(echo $?) -ne 0 ]];then echo "error";exit;fi
fi
done
